config/routes.rb
Rails.application.routes.draw do
  get "home/index"

  root "home#index"

  resources :categories
  resources :tasks

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true
    validates :user_id, presence: true
    
    has_many :tasks, dependent: :destroy 
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    validates :category_id, presence: true
    validates :task, presence: true
    
    belongs_to :category
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :categories, dependent: :destroy 
  has_many :tasks, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.where(user_id: current_user.id).order("name DESC") if user_signed_in?

  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.update(user_id: current_user.id)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    redirect_to categories_path, status: :see_other
    flash[:notice] = "Category was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index 
        @today_tasks = Task.where(created_at: Date.today.all_day, user_id: current_user.id).order("updated_at DESC") if user_signed_in?
        @all_tasks = Task.where(user_id: current_user.id).order("updated_at DESC") if user_signed_in?
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :set_categories

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.where(user_id: current_user.id).order("task DESC") if user_signed_in?
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)
    @task.update(user_id: current_user.id)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
    flash[:notice] = "Task was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task, :category_id, :user_id)
    end

    def set_categories
      @categories = Category.all.order(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div class="card text-bg-light mb-3" style="width: 18rem; margin-right: 10px">
  <div class="card-header">
    <%= category.name %>
    <span class="badge badge-primary" style="margin-left: 5px;"><%= category.tasks.count %></span>
  </div>
  <div class="card-body d-flex justify-content-around align-items-center">
            <%= link_to category, class: "btn btn-secondary" do %>
              Go To Category
            <% end %>

            <%= link_to edit_category_path(category.id) do %> 
              <span class="mr-1"><i class="bi bi-pen"></i></span>
            <% end %>
            
            <%= link_to category_path(category.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } do %>
              <span class="mr-1"><i class="bi bi-trash3"></i></span>
            <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="card">
  <div class="card-header">
    <h2>Editing Category</h2>
  </div>
  <div class="card-body">
    <%= render "form", category: @category %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this category", @category, class: "btn btn-secondary" %> |
  <%= link_to "Back to categories", categories_path, class: "btn btn-secondary" %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>

<div id="categories" class="d-flex flex-row flex-wrap">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>

<%= link_to "New Category", new_category_path, class: "btn btn-primary", style: "margin-top: 10px;"  %>

app/views/categories/new.html.erb
<div class="card">
  <div class="card-header">
    <h2>Create New category</h2>
  </div>
  <div class="card-body">
    <%= render "form", category: @category %>
  </div>
</div>

<br>

<div>
  <%= link_to "Back to categories", categories_path, class: "btn btn-secondary" %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

  <% @category.tasks.each do |task| %>
    <p>
    <%= task.task %> | <%= link_to "View Task", task %>
    </p>
  <% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <%= link_to "Journal App", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <!--category and task-->
        <% if user_signed_in? %>
          <li class="nav-item">
              <%= link_to "Categories", categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Tasks", tasks_path, class: "nav-link" %>
          </li>
      <!--devise-->
          <li class="nav-item">
              <%= link_to "Sign out", destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %>
          </li>
          <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<% if user_signed_in? %>
    <div id="tasks" class="d-flex flex-column justify-content-center align-items-center">
        <h2>Welcome back, <%= current_user.email.split("@")[0] %>!</h2>
        <p>
            <%= @today_tasks.count %> <%= "task".pluralize(@today_tasks.count) %> for today
            • 
            <%= Date.today.to_formatted_s(:long) %>
        </p>
    </div>

    <div id="tasks" class="d-flex flex-row justify-content-around align-items-center flex-wrap">
        <% @today_tasks.each do |task| %>
            <%= render task %>
        <% end %>
    </div>
<% else %>
    <h2>Please sign in to access your tasks.</h2>
<% end %>

app/views/layouts/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= alert %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/_notice.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Journal App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <%= render "home/header" %>
    <% if notice %>
      <%= render "layouts/notice" %>
    <% elsif alert %>
      <%= render "layouts/alert" %>
    <% end %>

    <div style="margin: 20px;"><%= yield %></div>
    

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :task, style: "display: block" %>
    <%= form.text_area :task, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(@categories.where(user_id: current_user.id).collect { |cat| [cat.name, cat.id] }) %>
  </div>

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="col-md-3 single-note-item all-category" style="margin-bottom: 20px;">
    <div class="card card-body">
        <span class="side-stick"></span>
        <h5 class="note-title text-truncate w-75 mb-0" data-noteheading="Category: <%= task.category.name %>">Category: <%= link_to task.category.name, task.category %></h5>
        <p class="note-date font-12 text-muted"><%= task.created_at %></p>
        <div class="note-content">
            <p class="note-inner-content text-muted" data-notecontent="Task: <%= task.task %>">Task: <%= task.task %></p>
        </div>
        <div class="d-flex align-items-center">
            <%= link_to edit_task_path(task.id) do %> 
                <span class="mr-1"><i class="bi bi-pen" style="margin-right: 15px;"></i></i></span>
            <% end %>
            
            <%= link_to task_path(task.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } do %>
              <span class="mr-1"><i class="bi bi-trash3"></i></span>
            <% end %>
        </div>
    </div>
</div>

app/views/tasks/edit.html.erb
<div class="card">
  <div class="card-header">
    <h2>Editing Task</h2>
  </div>
  <div class="card-body">
    <%= render "form", task: @task %>
  </div>
</div>

<br>

<div>
  <%= link_to "Show this task", @task, class: "btn btn-secondary", style: "margin-right: 10px;" %>
  <%= link_to "Back to tasks", tasks_path, class: "btn btn-secondary" %>
</div>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

<div id="tasks" class="d-flex flex-row align-items-center mx-auto flex-wrap">
  <% @tasks.each do |task| %>
    <%= render task %>
  <% end %>
</div>

<%= link_to "New task", new_task_path, class: "btn btn-primary", style: "margin-top: 10px;" %>

app/views/tasks/new.html.erb
<div class="card">
  <div class="card-header">
    <h2>Create New Task</h2>
  </div>
  <div class="card-body">
    <%= render "form", task: @task %>
  </div>
</div>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path, class: "btn btn-secondary" %>
</div>

app/views/tasks/show.html.erb
<%= render @task %>

<div>
  <%= link_to "Back to tasks", tasks_path, class: "btn btn-secondary", style: "margin-top: 10px;" %>
</div>